### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by Misteboss** [dktapps/PocketMine-C-ChunkUtils#2]
Hello,
Can tou explain me how to install it ?
I don't understand your README ^^
Where i have to place the folder or should i compile it and if yes how can i compile it ?

**Comment by NycuRO** [comment]
@dktapps Video? :D

**Comment by Muqsit** [comment]
Install it like you'd install any other PHP extension from source. It doesn't require a separate README as this is not a special pmmp-only extension, but a PHP extension.
This might help: http://lmgtfy.com/?q=How+to+install+PHP+extensions+from+source

**Comment by NycuRO** [comment]
@Muqsit Oh muqsit, hi :D I'm on your server, is very good :D

**Comment by NycuRO** [comment]
@dktapps Sorry if i bother you, but can you create one link for download or how i can compile with that?
